### ISSUE TITLE
README: Usage of :after_commit with transactional filters

### ISSUE THREAD

**Issue by krevels** [krisleech/wisper-activerecord#16]
It would be nice for there to be a brief note in the README about this gem's usage of the `:after_commit` callback, and it's effect on Rails tests which use transactional fixtures.  

Since `:after_commit` never fires for during the test's transaction, none of Wisper::ActiveRecord's events will fire either, leading to some head-scratching moments when testing.

This can be fixed by using the test_after_commit [gem](https://github.com/grosser/test_after_commit), and should no longer be an issue after the release of [Rails 5](https://github.com/rails/rails/pull/18458)

**Comment by ramkumarmk** [comment]
+1

**Comment by krisleech** [comment]
Agreed, please feel free to send a PR for the proposed changes.
