### ISSUE TITLE
Include attributes that have changed along with the model

### ISSUE THREAD

**Issue by wireframe** [krisleech/wisper-activerecord#17]
When using wisper listeners in async mode, the model no longer has what attributes have changed which is useful for only firing certain events if a particular attribute has changed.

One option would be to include the changed attributes along with the model so that the listener can inspect old values and perform logic as needed.

ex:

``` ruby
def after_update_broadcast
  broadcast(:after_update, self)
  broadcast("update_#{broadcast_model_name_key}_successful", self, self.previous_changes)
end
```

**Comment by krisleech** [comment]
This is a good idea. I was also thinking we should change the first argument to `self.id` (only for the second broadcast) as well since `self` will not work for async unless you are using ActiveJob which has proper support for deserializing to ActiveRecord.

It will be a breaking change, but since we are still version 0.x it should be okay.

**Comment by wireframe** [comment]
FWIW, there is a new gem that includes this functionality out of the box if anyone is interested in pursuing this further.  It allows for background job listeners to work as expected with activerecord events.
https://github.com/betterup/wisper-activerecord-publisher

**Comment by eppdot** [comment]
Did this got implemented?

**Comment by krisleech** [comment]
I don't think so, other than the gem linked to above, which I haven't tried myself. But you can do this with plain wisper events. Call `broadcast` from a ActiveRecord hook and include the model `id` and the `previous_changes` in the payload. You could wrap this up in a module if you need the functionality for multiple models. Hope this helps.
