### ISSUE TITLE
Event Naming Incorrect for Nested Models in Isolated Rails Engines

### ISSUE THREAD

**Issue by mattgoldman** [krisleech/wisper-activerecord#19]
Event names in Wisper are defined in part by `Model.model_name.param_key`. However, in an isolated Rails engine, the `param_key` isn't nested. So while an event for Business::Meeting should be named `create_business_meeting_successful`, it's actually not working that way since the `param_key` is equal to `meeting` instead of `business_meeting`.

Source: http://api.rubyonrails.org/classes/ActiveModel/Naming.html#method-c-param_key

At first glance, it seems like `#singular` would be a suitable replacement for `#param_key` but not sure if this would introduce other issues. I'm working on a replication of the issue + tests now.

**Comment by mattgoldman** [comment]
Closing this for now...although I was able to create failing tests and fix them by using `#singular`, I noticed that in my Rails app, the naming is working fine for my isolated engine. :confused: 

But events aren't firing for some other reason. Will update this if I find anything interesting.

**Comment by krisleech** [comment]
Thanks, so did you not need to use `singular` in the end?

By the way having a `return` in block listener can prevent other listeners from firing, http://product.reverb.com/2015/02/28/the-strange-case-of-wisper-and-ruby-blocks-behaving-like-procs/
