### ISSUE TITLE
Compatibility with Wisper 2.0.0

### ISSUE THREAD

**Issue by mattgoldman** [krisleech/wisper-activerecord#20]
Is it possible to make a branch with a gemspec compatible with wisper-2.0.0? 

We're using wisper-2.0.0.rc1 as well as wisper-activerecord-0.3.0.

Would submit a PR but not sure how you want to handle the versioning :smile:

**Comment by krisleech** [comment]
I *think* wisper-2.x should be compatible with wisper-ar-0.x, but that said it would be wise to branch and have a 2.x version even if there are no changes other than gemspec.

Maybe we should have wisper-ar-2.x which is compatible with wisper 2.x, what do you think?

**Comment by mattgoldman** [comment]
Sounds good to me...although I've spent very little time in the source of either, so I may not be the best one to ask :wink:

**Comment by krisleech** [comment]
The specs for this gem pass using Wisper 1 or 2. I will release a new version anyway shortly which depends on Wisper 2.0.
